name: Update servers.json

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-servers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Update servers.json
        run: go run ./cmd/gluetun update -maintainer -all

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code internal/storage/servers.json || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add internal/storage/servers.json
          git commit -m "chore(servers): update servers.json data

          🤖 Generated with GitHub Actions"
          git push